---
- name: Enable epel-release
  yum: name=epel-release state=installed

- name: Install ansible requirements
  yum: name={{item}} state=installed
  with_items:
    - libselinux-python
    - python-passlib

- name: Install betterplace tools
  yum: name={{item}} state=installed
  with_items:
    - bind-utils
    - gdb
    - git
    - htop
    - iotop
    - lsof
    - ltrace
    - man
    - mc
    - nc
    - nmap
    - screen
    - strace
    - telnet
    - tmux
    - tree
    - vim-enhanced
    - wget

- name: Install tmux confguration
  copy:
    src=tmux.conf
    dest=/etc/tmux.conf
    owner=root
    group=root
    mode=644
  tags: tmux

- name: Install system requirements
  yum: name={{item}} state=installed
  with_items:
    - gcc
    - gcc-c++
    - glibc-static
    - nfs-utils
    - patch
    - psutils
    - pv
    - readline-devel
    - rpm-build
    - rpmdevtools
    - yum-utils
    - libselinux-python
